import React, { useEffect, useState } from "react";

const REFLECTIONS = [
  "Respira, suelta y recuerda que estás haciendo lo mejor que puedes.",
  "Hoy es una nueva oportunidad para elegir un pensamiento que te haga bien.",
  "Pequeños pasos cuentan. Lo importante es seguir moviéndote.",
  "Nada cambia si no cambias algo.",
  "Tu intención guía tu camino.",
  "Hoy puedes comenzar diferente.",
  "Lo que haces hoy puede honrar a la persona que quieres ser mañana.",
  "Tu bienestar importa más de lo que crees.",
  "La calma es una práctica, no un destino.",
  "Tu energía es tu responsabilidad.",
  "Tu intención de hoy puede cambiar la forma en que ves todo.",
  "A veces avanzar es simplemente respirar y volver a intentarlo.",
  "Mereces la calma que estás aprendiendo a darte.",
  "Hoy puedes elegir una nueva dirección.",
  "No necesitas tener todo resuelto para empezar.",
  "Lo que siembras con intención florece con tiempo.",
  "Estás creciendo incluso cuando no lo notas.",
  "Tu paz interior es una prioridad, no un lujo.",
  "Lo que haces hoy puede honrar a la persona que quieres ser mañana.",
  "Agradece lo que eres mientras trabajas por lo que deseas.",
  "Da el primer paso, aunque sea pequeño.",
  "Hoy puedes empezar de nuevo.",
  "Tu bienestar importa más de lo que crees.",
  "La claridad viene cuando respiras y escuchas tu interior.",
  "No estás atrasado, estás en tu propio tiempo.",
  "Todo cambio significativo comienza con una decisión pequeña.",
  "Confía en el proceso, incluso cuando parece lento.",
  "Lo que buscas también te está buscando a ti.",
  "Sé amable contigo mientras avanzas.",
  "Tu intención guía tu camino.",
  "Siempre hay espacio para una nueva versión de ti.",
  "El miedo es solo una señal de que estás creciendo.",
  "Cada día puedes elegir sentir distinto.",
  "La calma no llega, se crea.",
  "Solo por hoy, avanza un paso más.",
  "Lo que te pesa hoy te hará más fuerte mañana.",
  "Tu enfoque determina tu energía.",
  "Mereces sentir orgullo por tus pequeños avances.",
  "Si escuchas con paz, encontrarás la respuesta.",
  "Tu historia apenas está comenzando.",
  "Lo que amas también te construye.",
  "No tienes que correr, solo avanzar.",
  "Hoy puedes cuidar de ti sin culpa.",
  "No subestimes el poder de una intención clara.",
  "Lo que repites se convierte en tu vida.",
  "Tu propósito se revela cuando te permites sentir.",
  "Puedes soltar sin olvidar, puedes avanzar sin herirte.",
  "La vida cambia cuando tú cambias.",
  "Hoy puedes elegir lo que te hace bien.",
  "Tu luz interior es más fuerte de lo que crees.",
  "Escucha el silencio, ahí vive tu verdad.",
  "La disciplina nace del amor propio, no de la exigencia.",
  "No necesitas hacer más, necesitas ser más tú.",
  "Tu intención es el primer acto de transformación.",
  "La calma es una práctica, no un destino.",
  "Plantar una intención es regalarte dirección.",
  "Estás aprendiendo a cuidarte, y eso es hermoso.",
  "Lo que piensas sobre ti importa más que lo que piensan los demás.",
  "Eres suficiente incluso mientras evolucionas.",
  "La vida te habla cuando desaceleras.",
  "Hoy puedes mostrarte vulnerable y aun así ser fuerte.",
  "No estás perdido, estás recalculando.",
  "Date permiso de sentir sin juzgarte.",
  "La constancia te llevará donde la motivación no puede.",
  "Nada cambia si no cambias algo.",
  "Tu intención de hoy puede ser tu ancla emocional.",
  "La claridad aparece cuando sueltas lo que te confunde.",
  "Lo que haces por ti, nadie puede quitártelo.",
  "Estás más cerca de lo que crees.",
  "Tu voz interior ya sabe lo que necesitas.",
  "No ignores tu paz por complacer a otros.",
  "Cada avance, por pequeño que sea, es progreso.",
  "Escoge pensamientos que te nutran.",
  "Tu fuerza aparece cuando más la necesitas.",
  "Aceptarte es el primer paso para transformarte.",
  "Una intención clara puede cambiar un día entero.",
  "Hoy también cuenta.",
  "Tienes el poder de crear tu propio ritmo.",
  "Tu vida cambia cuando cambias tu enfoque.",
  "No fuerces, permite.",
  "Estás evolucionando de maneras que aún no ves.",
  "Tu bienestar empieza por escucharte.",
  "Lo que haces hoy puede sanar al futuro tú.",
  "Tienes derecho a descansar sin sentir culpa.",
  "La inspiración llega cuando te encuentras contigo.",
  "Elige el camino que te hace sentir auténtico.",
  "No te compares; tu proceso es único.",
  "Cada día es una oportunidad para comenzar diferente.",
  "Tu mente necesita la misma atención que tu cuerpo.",
  "Estás justo donde necesitas estar.",
  "La intención transforma incluso los días simples.",
  "La respuesta está en ti, no afuera.",
  "Lo que haces con intención siempre regresa multiplicado.",
  "El progreso no siempre se ve, pero se siente.",
  "Permítete avanzar sin tener todas las certezas.",
  "Lo que valoras te muestra quién eres.",
  "La calma empieza cuando decides detenerte.",
  "Tu energía es tu responsabilidad.",
  "No te sueltes justo antes de ver el milagro.",
  "Recuerda por qué comenzaste.",
  "Cada día puedes escoger amar mejor, incluso a ti mismo.",
  "Tu equilibrio emocional es un acto de amor propio.",
  "Lo que se siente pesado hoy puede ser sabiduría mañana.",
  "No eres tus dudas, eres tu intención de superarlas.",
  "Lo que haces con claridad nunca se desperdicia.",
  "Tu alma ya sabe el camino.",
  "Hoy puedes ser más consciente, más ligero, más tú.",
  "Estás sembrando versiones de ti que aún no conoces.",
  "La intención correcta hace que todo fluya distinto.",
  "Hoy es un buen día para renacer.",
];

export default function DailyReflection() {
  const [reflection, setReflection] = useState("");

  useEffect(() => {
    const random = REFLECTIONS[Math.floor(Math.random() * REFLECTIONS.length)];
    setReflection(random);
  }, []);

  return (
    <div className="card">
      <div className="card-header">
        <span className="card-title">Reflexión del día</span>
      </div>

      <p className="reflection-text">{reflection}</p>
    </div>
  );
}
